[package]
name = "flint-ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
mlua = "0.10.3"
serde = "1.0.219"
serde_json = "1.0.140"
serde_yaml = "0.9.34"
sqlx = "0.8.3"
toml = "0.8.20"
flint-utils = { path = "../flint-utils" }
smol = "2.0.2"
