[flint]
version = 1

[common]
# Basic style settings
indent_style = "spaces"
indent_size = 2
max_line_length = 100
quote_style = "double"
require_semicolons = false


[rules.eslint]

[config.eslint]
# root = "./flint-tests/src/js"
# ignore = ["node_modules", "coverage"]

[tests.jest]
# testEnvironment = "node"
# testMatch = ["**/tests/**/*.test.js"]
# collectCoverage = true

[ci]

[report]

[ci.github-actions]

[report.json]
outputPath = "reports"
